# Generated by Django 3.0.5 on 2020-07-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactus',
            new_name='contact_details',
        ),
    ]
