# Generated by Django 2.2.14 on 2020-07-17 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0020_auto_20200714_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_details',
            name='name',
        ),
        migrations.AddField(
            model_name='contact_details',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
