# Generated by Django 2.2.14 on 2020-07-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200717_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_details',
            name='user',
        ),
        migrations.AddField(
            model_name='contact_details',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
