# Generated by Django 2.2.14 on 2020-07-20 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='apartment_address',
            new_name='appartment_address',
        ),
    ]
