# Generated by Django 2.2.14 on 2020-07-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20200723_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear'), ('CA', 'Casuals'), ('AC', 'Accessories')], max_length=2),
        ),
    ]
